// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.33.1
// source: proto/sum/sum.proto

package sumpb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SumNumbersRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             int32                  `protobuf:"varint,1,opt,name=x,proto3" json:"x,omitempty"`
	Y             int32                  `protobuf:"varint,2,opt,name=y,proto3" json:"y,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumNumbersRequest) Reset() {
	*x = SumNumbersRequest{}
	mi := &file_proto_sum_sum_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumNumbersRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumNumbersRequest) ProtoMessage() {}

func (x *SumNumbersRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sum_sum_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumNumbersRequest.ProtoReflect.Descriptor instead.
func (*SumNumbersRequest) Descriptor() ([]byte, []int) {
	return file_proto_sum_sum_proto_rawDescGZIP(), []int{0}
}

func (x *SumNumbersRequest) GetX() int32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SumNumbersRequest) GetY() int32 {
	if x != nil {
		return x.Y
	}
	return 0
}

type SumNumbersResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Z             int32                  `protobuf:"varint,1,opt,name=z,proto3" json:"z,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SumNumbersResponse) Reset() {
	*x = SumNumbersResponse{}
	mi := &file_proto_sum_sum_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SumNumbersResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SumNumbersResponse) ProtoMessage() {}

func (x *SumNumbersResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_sum_sum_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SumNumbersResponse.ProtoReflect.Descriptor instead.
func (*SumNumbersResponse) Descriptor() ([]byte, []int) {
	return file_proto_sum_sum_proto_rawDescGZIP(), []int{1}
}

func (x *SumNumbersResponse) GetZ() int32 {
	if x != nil {
		return x.Z
	}
	return 0
}

var File_proto_sum_sum_proto protoreflect.FileDescriptor

const file_proto_sum_sum_proto_rawDesc = "" +
	"\n" +
	"\x13proto/sum/sum.proto\x12\x03sum\"/\n" +
	"\x11SumNumbersRequest\x12\f\n" +
	"\x01x\x18\x01 \x01(\x05R\x01x\x12\f\n" +
	"\x01y\x18\x02 \x01(\x05R\x01y\"\"\n" +
	"\x12SumNumbersResponse\x12\f\n" +
	"\x01z\x18\x01 \x01(\x05R\x01z2T\n" +
	"\x11SumNumbersService\x12?\n" +
	"\n" +
	"SumNumbers\x12\x16.sum.SumNumbersRequest\x1a\x17.sum.SumNumbersResponse\"\x00B4Z2github.com/aelhady03/sumflow/adder/proto/sum;sumpbb\x06proto3"

var (
	file_proto_sum_sum_proto_rawDescOnce sync.Once
	file_proto_sum_sum_proto_rawDescData []byte
)

func file_proto_sum_sum_proto_rawDescGZIP() []byte {
	file_proto_sum_sum_proto_rawDescOnce.Do(func() {
		file_proto_sum_sum_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_sum_sum_proto_rawDesc), len(file_proto_sum_sum_proto_rawDesc)))
	})
	return file_proto_sum_sum_proto_rawDescData
}

var file_proto_sum_sum_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_proto_sum_sum_proto_goTypes = []any{
	(*SumNumbersRequest)(nil),  // 0: sum.SumNumbersRequest
	(*SumNumbersResponse)(nil), // 1: sum.SumNumbersResponse
}
var file_proto_sum_sum_proto_depIdxs = []int32{
	0, // 0: sum.SumNumbersService.SumNumbers:input_type -> sum.SumNumbersRequest
	1, // 1: sum.SumNumbersService.SumNumbers:output_type -> sum.SumNumbersResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_proto_sum_sum_proto_init() }
func file_proto_sum_sum_proto_init() {
	if File_proto_sum_sum_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_sum_sum_proto_rawDesc), len(file_proto_sum_sum_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_sum_sum_proto_goTypes,
		DependencyIndexes: file_proto_sum_sum_proto_depIdxs,
		MessageInfos:      file_proto_sum_sum_proto_msgTypes,
	}.Build()
	File_proto_sum_sum_proto = out.File
	file_proto_sum_sum_proto_goTypes = nil
	file_proto_sum_sum_proto_depIdxs = nil
}
