// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v6.33.1
// source: proto/sum/sum.proto

package sumpb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SumNumbersService_SumNumbers_FullMethodName = "/sum.SumNumbersService/SumNumbers"
)

// SumNumbersServiceClient is the client API for SumNumbersService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SumNumbersServiceClient interface {
	SumNumbers(ctx context.Context, in *SumNumbersRequest, opts ...grpc.CallOption) (*SumNumbersResponse, error)
}

type sumNumbersServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSumNumbersServiceClient(cc grpc.ClientConnInterface) SumNumbersServiceClient {
	return &sumNumbersServiceClient{cc}
}

func (c *sumNumbersServiceClient) SumNumbers(ctx context.Context, in *SumNumbersRequest, opts ...grpc.CallOption) (*SumNumbersResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SumNumbersResponse)
	err := c.cc.Invoke(ctx, SumNumbersService_SumNumbers_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SumNumbersServiceServer is the server API for SumNumbersService service.
// All implementations must embed UnimplementedSumNumbersServiceServer
// for forward compatibility.
type SumNumbersServiceServer interface {
	SumNumbers(context.Context, *SumNumbersRequest) (*SumNumbersResponse, error)
	mustEmbedUnimplementedSumNumbersServiceServer()
}

// UnimplementedSumNumbersServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSumNumbersServiceServer struct{}

func (UnimplementedSumNumbersServiceServer) SumNumbers(context.Context, *SumNumbersRequest) (*SumNumbersResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SumNumbers not implemented")
}
func (UnimplementedSumNumbersServiceServer) mustEmbedUnimplementedSumNumbersServiceServer() {}
func (UnimplementedSumNumbersServiceServer) testEmbeddedByValue()                           {}

// UnsafeSumNumbersServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SumNumbersServiceServer will
// result in compilation errors.
type UnsafeSumNumbersServiceServer interface {
	mustEmbedUnimplementedSumNumbersServiceServer()
}

func RegisterSumNumbersServiceServer(s grpc.ServiceRegistrar, srv SumNumbersServiceServer) {
	// If the following call pancis, it indicates UnimplementedSumNumbersServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SumNumbersService_ServiceDesc, srv)
}

func _SumNumbersService_SumNumbers_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SumNumbersRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SumNumbersServiceServer).SumNumbers(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SumNumbersService_SumNumbers_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SumNumbersServiceServer).SumNumbers(ctx, req.(*SumNumbersRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SumNumbersService_ServiceDesc is the grpc.ServiceDesc for SumNumbersService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SumNumbersService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "sum.SumNumbersService",
	HandlerType: (*SumNumbersServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SumNumbers",
			Handler:    _SumNumbersService_SumNumbers_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/sum/sum.proto",
}
